# Generated by Django 5.1.2 on 2024-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_jobposting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='category',
            field=models.TextField(default='General'),
        ),
    ]
