# Generated by Django 5.1.2 on 2024-12-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_jobposting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=250)),
            ],
        ),
    ]
