# Generated by Django 5.1.2 on 2024-12-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_jobcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='jobcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_board.jobcategories'),
        ),
    ]
